name = "CovarianceDynamics"
uuid = "9c6c2b8a-8cdd-4f41-9e3c-2e1d3e4f1a77"
version = "0.1.0"

[deps]

SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"

